### Create a new patient entity
POST http://localhost:4005/api/doctor-service/v1/create-doctor
Content-Type: application/json

{
  "firstName": "testing",
  "lastName": "testing",
  "phoneNumber": "+62856335127866",
  "email": "testing.testing@hospital.com"
}

###