spring.application.name=billing-service

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=4001
grpc.server.port=9001