### Create a new patient entity
POST http://localhost:4000/api/patient-service/v1/create-patient
Content-Type: application/json

{
  "firstName": "Nezha",
  "lastName": "Nezha",
  "phoneNumber": "+62858813294",
  "email": "nezha.nezha@example.com",
  "address": "Jl. Sudirman No. 456, Malang",
  "dateOfBirth": "1990-05-15",
  "gender": "MALE"
}

###