spring.application.name=patient-service

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none

server.port=4000
logging.level.root=info